language: csharp

matrix:
  include:
    - os: linux # Ubuntu 16.04
      dist: xenial
      sudo: required
      dotnet: 2.2.203
    - os: osx # OSX 10.12
      osx_image: xcode9.1
      dotnet: 2.2.203
      dist: trusty
      sudo: required

install:
  # workaround for missing .net 4.5.2 targeting pack
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5.2/

script: 
  - ./build.sh All

branches:
  except:
    - gh-pages