environment:
  CLI_VERSION: 2.2.203
image: Visual Studio 2017
init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd All
test: off
version: 1.14.0-b{build}
artifacts:
  - path: bin/FSharpx.Async.*.nupkg
    name: nupkg
